on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "login to decker"
        run: docker login --username ${{secrets.DOCKER_USER}} --password ${{secrets.DOCKER_PASS}}
      
      - name: "build image in docker"
        run: docker build -t ${{secrets.DOCKER_USER}}/mygitImage .

      - name: "push to docker hub"
        run: docker push ${{secrets.DOCKER_USER}}/mygitImage