on:
  push:
    branches:
      - master





job:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "login to decker"
      run: docker login --username ${{secrets.DOCKER_USER}} --password ${{secrets.DOCKER_PASS}}